project: 
  type: website
  output-dir: docs

website: 
  title: "Kai Suzuki"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About
      - href: project.qmd
        text: Project
      - href: running.qmd
        text: Running
      - href: resume.qmd
        text: Resume

format:
  html: 
    theme: brightside
    