---
title: "Running"
format: html
---

# Beginnings

For as long as I can remember, I have been involved in all kinds of sports. Despite not having much success in soccer and baseball, they set a strong competitive baseline in me. In my sophomore year of high school, I joined the track team where my perfect attendance at practices and consistent work led to improvement and two captain roles. I really cherished my short three years with the team, but I left discouragement after a frustrating senior year of injuries and underwhelming results.

# Consistency

During my time in community college, I never got into a routine of running. Once I moved into my apartment after transferring schools, I had the North Campus Open Space and the Elwood Mesa as my backyard. Having the rare combination of clean air, endless dirt trails, and year-round greenery made running much more enjoyable than the concrete sidewalks of my suburban hometown. Running is something I look forward to and I try to fit about three runs a week into my schedule. 

# Accessiblity

Social media discourse in 2025 about a [running influencer collaborating with the White House Press Secretary](https://www.thecut.com/article/tiktok-controversy-kate-mackz-karoline-leavitt-interview.html){target="_blank"} brought massive attention to how interconnected running and politics are. An administration that [guts clean air regulations](https://www.pbs.org/newshour/politics/epa-head-announces-sweeping-plan-to-revoke-dozens-of-environmental-regulations){target="_blank"}, [cuts programs that provide healthy food to kids](https://www.edweek.org/policy-politics/trump-admin-cuts-program-that-brought-local-food-to-school-cafeterias/2025/03){target="_blank"}, and [targets transgender athletes](https://williamsinstitute.law.ucla.edu/publications/impact-trans-sports-ban-eo/){target="_blank"}, should not be welcomed by the running community. The conversation made me further realize how much of a privilege it is to run with access to adequate food and gear. It is a goal of mine to work towards making running more accessible through tangible actions, such as working with the Associated Students of UCSB's [Edible Campus Program](https://www.sustainability.ucsb.edu/giving/edible-campus-program){target="_blank"} and [Department of Public Worms](https://worms.as.ucsb.edu/){target="_blank"} who both help fight food insecurity on campus by providing fresh produce to all students. 

# Where you might see me running!

<!-- Add script to the <head> of your page to load the embeddable map component -->
<script type="module" src="https://js.arcgis.com/embeddable-components/4.32/arcgis-embeddable-components.esm.js"></script>
<!-- Add custom element to <body> of your page -->
 <arcgis-embedded-map style="height:600px;width:700px;" item-id="49956827248648ed8a17a8a424492ccc" theme="light" portal-url="https://ucsb.maps.arcgis.com" ></arcgis-embedded-map>
 